name: github action test

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Jab:
    runs-on: ubuntu-latest
    steps:
      - name: hellow 찍기
        run: echo "Hello world"
      - name: 여러명령어 넣기
        run: |
          echo "good"
          echo "morning"
